# Generated by Django 5.0 on 2023-12-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=15)),
                ('instagram', models.CharField(max_length=15)),
                ('x', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='imagenes/%Y/%m/%d')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisico', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DanchArtApp.base')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DanchArtApp.cliente')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DanchArtApp.foto')),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DanchArtApp.foto'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrega', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DanchArtApp.cliente')),
            ],
        ),
    ]
