# Generated by Django 5.0 on 2023-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanchArtApp', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
