# Generated by Django 5.0 on 2023-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanchArtApp', '0003_cuadro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='tipo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
