# Generated by Django 5.0 on 2023-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanchArtApp', '0005_cliente_email_cuadro_nombre_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='foto',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
