# Generated by Django 5.0 on 2023-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanchArtApp', '0006_alter_cuadro_tipo_alter_foto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
